"""aaa

Revision ID: 16e7172020b1
Revises: 601d13ba0650
Create Date: 2025-04-09 17:36:13.561713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16e7172020b1'
down_revision = '601d13ba0650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trading_instrument', sa.Column('change', sa.Float(), nullable=True))
    op.add_column('trading_instrument', sa.Column('previous_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trading_instrument', 'previous_price')
    op.drop_column('trading_instrument', 'change')
    # ### end Alembic commands ###
