"""trade analyics

Revision ID: 1fc79a05b26a
Revises: 3ad22b10e5ea
Create Date: 2025-04-21 02:06:38.593730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fc79a05b26a'
down_revision = '3ad22b10e5ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('trade', sa.Column('leverage', sa.Float(), 
                                     server_default='1.0',
                                     nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade', 'notes')
    op.drop_column('trade', 'leverage')
    # ### end Alembic commands ###
