"""Add credit_balance column to Lead model

Revision ID: 3ad22b10e5ea
Revises: 16e7172020b1
Create Date: 2025-04-16 17:24:51.880830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ad22b10e5ea'
down_revision = '16e7172020b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead', sa.Column('credit_balance', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead', 'credit_balance')
    # ### end Alembic commands ###
