"""Add opening_date and closing_date to Trade model

Revision ID: 4cfed34a4e0f
Revises: 
Create Date: 2025-04-07 13:11:12.877408

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = '4cfed34a4e0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('trade', sa.Column('closing_date', sa.DateTime(), nullable=True)) # Commented out as it likely already exists
    
    # Use server_default for SQLite compatibility
    current_time = datetime.utcnow()
    op.add_column('trade', sa.Column('opening_date', sa.DateTime(), 
                                     server_default=sa.text("'{}'"
                                     .format(current_time.strftime('%Y-%m-%d %H:%M:%S'))),
                                     nullable=False))
    
    # Update the opening_date field to match the date field
    op.execute("UPDATE trade SET opening_date = date")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade', 'opening_date')
    op.drop_column('trade', 'closing_date')
    # ### end Alembic commands ###
