"""Add description field to LeadStatus model

Revision ID: 5a0f6ac97055
Revises: 11275332481d
Create Date: 2025-04-28 11:01:44.414417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a0f6ac97055'
down_revision = '11275332481d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_lead_source_api_key'), 'lead_source', ['api_key'])
    op.create_unique_constraint(op.f('uq_lead_source_source_name'), 'lead_source', ['source_name'])
    op.add_column('lead_status', sa.Column('color', sa.String(length=20), nullable=True))
    op.add_column('lead_status', sa.Column('description', sa.String(length=100), nullable=True))
    op.create_unique_constraint(op.f('uq_lead_status_status_name'), 'lead_status', ['status_name'])
    op.create_unique_constraint(op.f('uq_role_name'), 'role', ['name'])
    op.create_unique_constraint(op.f('uq_trading_instrument_symbol'), 'trading_instrument', ['symbol'])
    op.create_unique_constraint(op.f('uq_user_email'), 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_email'), 'user', type_='unique')
    op.drop_constraint(op.f('uq_trading_instrument_symbol'), 'trading_instrument', type_='unique')
    op.drop_constraint(op.f('uq_role_name'), 'role', type_='unique')
    op.drop_constraint(op.f('uq_lead_status_status_name'), 'lead_status', type_='unique')
    op.drop_column('lead_status', 'description')
    op.drop_column('lead_status', 'color')
    op.drop_constraint(op.f('uq_lead_source_source_name'), 'lead_source', type_='unique')
    op.drop_constraint(op.f('uq_lead_source_api_key'), 'lead_source', type_='unique')
    # ### end Alembic commands ###
