"""aaa

Revision ID: 5c9baad21647
Revises: 4cfed34a4e0f
Create Date: 2025-04-08 19:30:29.017364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c9baad21647'
down_revision = '4cfed34a4e0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal', sa.Column('probability', sa.Integer(), nullable=False, server_default='50'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deal', 'probability')
    # ### end Alembic commands ###
