"""Make company_name nullable and update lead fields

Revision ID: 601d13ba0650
Revises: 5c9baad21647
Create Date: 2025-04-09 17:11:29.970143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision = '601d13ba0650'
down_revision = '5c9baad21647'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support ALTER TABLE ... DROP NOT NULL
    # We need to manually create a new table and copy the data
    
    # Get the current table columns
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    columns = inspector.get_columns('lead')
    
    # Create a new table with the desired schema
    with op.batch_alter_table('lead', recreate='always') as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', recreate='always') as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    # ### end Alembic commands ###
