"""added profile pictures for clients 

Revision ID: 8d78a1b16fa2
Revises: 1c309da2fbd8
Create Date: 2025-04-25 01:04:47.397262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d78a1b16fa2'
down_revision = '1c309da2fbd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead', sa.Column('profile_image', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead', 'profile_image')
    # ### end Alembic commands ###
