"""Add available_to_trade column to Lead model

Revision ID: b62322e0bf25
Revises: 1fc79a05b26a
Create Date: 2025-04-22 17:09:23.136249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b62322e0bf25'
down_revision = '1fc79a05b26a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead', sa.Column('available_to_trade', sa.Boolean(), nullable=False, server_default=sa.text('1')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead', 'available_to_trade')
    # ### end Alembic commands ###
