"""Add API key and affiliate ID to LeadSource

Revision ID: de1f187d2bb7
Revises: 8d78a1b16fa2
Create Date: 2025-04-25 13:26:46.067045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de1f187d2bb7'
down_revision = '8d78a1b16fa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed drop_table operations since tables have already been removed
    op.add_column('lead_source', sa.Column('affiliate_id', sa.String(length=40), nullable=True))
    op.add_column('lead_source', sa.Column('api_key', sa.String(length=64), nullable=True))
    op.add_column('lead_source', sa.Column('is_api_enabled', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'lead_source', ['api_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lead_source', type_='unique')
    op.drop_column('lead_source', 'is_api_enabled')
    op.drop_column('lead_source', 'api_key')
    op.drop_column('lead_source', 'affiliate_id')
    # Removed create_table operations for account and contact tables
    # ### end Alembic commands ###
